FROM java:8

ADD /tmp/khs-trouble-maker.jar /khs-trouble-maker.jar

# so that it has a file modification time (Docker creates all container files in an "unmodified" state by default)
RUN bash -c 'touch /khs-trouble-maker.jar'

EXPOSE 8080

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/khs-trouble-maker.jar"]
